[theme]

## HARDWOOD THEME ##
primaryColor="#2BDB6B" #alien green 2
backgroundColor= "#1A1A1D" #"" #hardwoodlightbrown attempts: #"#E9D0AF" #E4C49B  #DEB887 
secondaryBackgroundColor="#020202" #spacegray
textColor= "#C39C76" #"#F29539" #"#1A1A1D" #spaceblack 
font="sans serif"


## COLOR LIBRARY ##

#dark-blue2:"#152238"
#dark-blue-OG:"#001440"
#dark-black: "#1B1E1F"
#space-black: "#1A1A1D"
#space-black2: "#17252A"
#space-black3: "#19181A"
#space-gray:"#282828"
#space-gray2: "#2C3531"
#LIGHT-BROWN: "#DEB887"


#alien-green-OG: "#EDF5E1"
#alien-green2: "#2BDB6B"
#bright-teal: "#66FCF1"


## SPACE THEME ##
# primaryColor="#66FCF1"
# backgroundColor="#1A1A1D" #"#1B1E1F"
# secondaryBackgroundColor="#020202"
# textColor="#66FCF1"
# font="monospace"

## MIAMI VICE ##
# primaryColor="#07efdb"
# backgroundColor="#02619C"
# secondaryBackgroundColor="#0a0a0a"
# textColor="#c00ce4"
# font="sans serif"

## G+B ##
# primaryColor="#5CD895"
# backgroundColor="#05386B"
# secondaryBackgroundColor="#8EE4AF"
# textColor="#EDF5E1"
# font="monospace"
